# CS 109A/STAT 121A/AC 209A/CSCI E-109A

## Standard Section 2: Webscraping with BeautifulSoup, Continued

**Harvard University**<br/>
**Fall 2017**<br/>
**Section Leaders: Nathaniel Burbank, Albert Wu, Matthew Holman <br/>**
**Instructors: Pavlos Protopapas, Kevin Rader, Rahul Dave, Margo Levine**

<center>**Download this notebook from CS109 repo or here: <br> http://bit.ly/109_s2 **</center>


During the first section we worked with tables of historic population estimates of the different US states, as listed on the Wikipedia site: https://en.wikipedia.org/wiki/List_of_U.S._states_by_historical_population.  We learned how to download a webpage via its URL, to parse the resulting html into a python object with BeautifulSoup, to extract the necessary tables, to convert the results into a pandas dataframe, and finally to make a few plots.

In this section, we will extend those results to include the median household income and other information per state. 
Specifically, we will: 
    
    1. Review the process of downloading a webpage with the requests library 
    2. Revisit how to parse the html into a python object using the BeautifulSoup library
    3. Again use BeautifulSoup to select and extract the relevant tables
    4. Clean the text and convert the table into a python dictionary 
    5. Save and restore the results in files with JSON and csv (pandas)
    6. Make a pandas dataframe from the dictionary
    7. Join the new dataframe with the one we made last week.
    8. Inner vs outer joins 
    9. Do more analysis and plotting (with matplotlib)

As usual, our first step is to import the necessary libraries.

In [1]:
%matplotlib inline
import sys
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

import requests 
requests.packages.urllib3.disable_warnings()
#Requests enables us to download raw html as text
from bs4 import BeautifulSoup 
# BeautifulSoup enables us to navigate html in python with dom-like tree structure 

# Two new ones
import time
# So that we can sleep between downloads
import json
# We'll write and read JSON files later

assert(sys.version_info.major==3),print(sys.version)
# Python 3 or higher is required

## Download, extract, and parse the relevant webpage as raw html

Next, let's quickly reconstruct the pandas dataframe we made in the last section.  Recall that we

    1. used the requests module to download the page corresponding to a given URL,
    2. extracted the raw HTML of the result, and
    3. used BeautifulSoup to parse the raw HTML.
    
We could repeat each of these steps, but you might have noticed that we only used the final result and ignored the intermediate results.  This calls out for a function definition.

In [2]:
# Dictionary to store already downloaded BeautifulSoup objects 
html_cache = dict()

In [3]:
def dl_parsed_html(url, timeout=20, verify=False, sleep_time=1):
    """Downloads the content of the page specified by url.
    Return the parsed HTML or None upon error.
    Notice that timeout, verify, and sleep_time have 
    defaults values"""
    
    # Down load the context at url
    r = requests.get(url, timeout=20,verify=False)
    
    # Check if HTTP status code is anything other than "ok"
    if r.status_code != 200:
        return None
    
    # Grab the raw HTML of the result
    raw_html = r.text
    
    # Parse the raw HTML with Beautiful soup
    soup = BeautifulSoup(raw_html, 'html.parser')
    
    # We have added a default 1 sec sleep
    time.sleep(sleep_time)
    
    # Return the parsed results
    return soup

def get_parsed_html(url, timeout=20, verify=False, sleep_time=1):
    """If we’ve already downloaded a webpage, return from cache. 
    Otherwise, download and parse using dl_parsed_html above."""
    if url not in html_cache:
        parsed_html = dl_parsed_html(url, timeout, verify, sleep_time)
        if parsed_html:
            html_cache[url] = parsed_html 
            
    return html_cache.get(url,None)

Now let's use our new function to download and parse the US historical population information again.

In [4]:
soup = get_parsed_html("http://en.wikipedia.org/wiki/List_of_U.S._states_by_historical_population")
soup.find('title').text

'List of U.S. states by historical population - Wikipedia'

We can use find_all to get the tables of interest again.

In [5]:
tables = soup.find_all("table",attrs={"class":"wikitable"})
# This says return a list of all table objects that include 
# the css class “wikitable” within the soup object.  

# We only need the first, third, and fourth tables.
tables = [tables[0], tables[2], tables[3]]

We can render the first table, to inspect it, as we did in the previous section.

In [6]:
from IPython.core.display import display, HTML
display(HTML(tables[0].prettify()))

## Clean data and build dictionary

Here is the code we used in the previous section to clean the data and build the dictionary, row by row, from a list of tables.

In [7]:
def rm_footnotes(s):
    """Removes any text after first '[' in string
    District of Columbia[1] -> District of Columbia"""
    return s.split('[')[0]

def clean_int(s):
    """Removes any commas, '$' symbols, or footnotes from string and converts to int.
    Returns zero for blank strings"""
    s = s.strip().replace(',','').replace('$', '')
    s = rm_footnotes(s)
    return int(s) if s else 0

In [12]:
d = dict()

for table in tables:
    """Extracts population data for states from all tables in tables 
      and store it in single dictionary d """
    
    headrow = table.find("tr")
    
    col_names = [(idx,th.text) for idx,th in enumerate(headrow.find_all('th')) if th.text.isnumeric()]
    # Makes list of tuples like this with idx and name for cols with years.
    # By using isnumeric, we only include columns are that are years. 
    # Result looks like this: 
    # [(2, '1790'), (3, '1800'), (4, '1810')]                     
    
    rows = table.find_all("tr")[1:]
    # List of rows in table excluding the header row 
    
    for row in rows:
        state_name = rm_footnotes(row.find('td').text)
        # String of state name, with any footnotes removed 
        
        all_cells = [c.text for c in row.find_all('td')]
        # List of cell values for row, e.g.: 
        # ['Alabama', '1819', '\xa0', '1,250', '9,046' .. ] 
        
        existing_values = d.get(state_name,{})
        # Existing dict of values for given state 
        
        new_values = {year:clean_int(all_cells[idx]) for (idx,year) in col_names}
        # For cols listed in col_names, return dict of cleaned int values 
        # {'1790': 0, '1800': 1250, '1810': 9046...}
        
        existing_values.update(new_values)
        # Merge with existing dict for state 
        d[state_name] = existing_values

In [13]:
d

{'Alabama': {'1790': 0,
  '1800': 1250,
  '1810': 9046,
  '1820': 127901,
  '1830': 309527,
  '1840': 590756,
  '1850': 771623,
  '1860': 964201,
  '1870': 996992,
  '1880': 1262505,
  '1890': 1513017,
  '1900': 1828697,
  '1910': 2138093,
  '1920': 2348174,
  '1930': 2646248,
  '1940': 2832961,
  '1950': 3061743,
  '1960': 3266740,
  '1970': 3444165,
  '1980': 3893888,
  '1990': 4040587,
  '2000': 4447100,
  '2010': 4779736},
 'Alaska': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 33426,
  '1900': 32052,
  '1910': 64356,
  '1920': 55036,
  '1930': 59278,
  '1940': 72524,
  '1950': 128643,
  '1960': 226167,
  '1970': 300382,
  '1980': 401851,
  '1990': 550043,
  '2000': 626932,
  '2010': 710231},
 'Arizona': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 9658,
  '1880': 40440,
  '1890': 88243,
  '1900': 122931,
  '1910': 204354,
  '1920': 334162,
  '1930': 435573,
  '1940': 499261,
  '1950': 749587,
  '1960': 1302161,
  '1970': 1770900,
  '1980': 2718215,
  '1990': 3665228,
  '2000': 5130632,
  '2010': 6392017},
 'Arkansas': {'1790': 0,
  '1800': 0,
  '1810': 1062,
  '1820': 14273,
  '1830': 30388,
  '1840': 97574,
  '1850': 209897,
  '1860': 435450,
  '1870': 484471,
  '1880': 802525,
  '1890': 1128211,
  '1900': 1311564,
  '1910': 1574449,
  '1920': 1752204,
  '1930': 1854482,
  '1940': 1949387,
  '1950': 1909511,
  '1960': 1786272,
  '1970': 1923295,
  '1980': 2286435,
  '1990': 2350725,
  '2000': 2673400,
  '2010': 2915918},
 'California': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 92597,
  '1860': 379994,
  '1870': 560247,
  '1880': 864694,
  '1890': 1213398,
  '1900': 1485053,
  '1910': 2377549,
  '1920': 3426861,
  '1930': 5677251,
  '1940': 6907387,
  '1950': 10586223,
  '1960': 15717204,
  '1970': 19953134,
  '1980': 23667902,
  '1990': 29760021,
  '2000': 33871648,
  '2010': 37253956},
 'Colorado': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 34277,
  '1870': 39864,
  '1880': 194327,
  '1890': 413249,
  '1900': 539700,
  '1910': 799024,
  '1920': 939629,
  '1930': 1035791,
  '1940': 1123296,
  '1950': 1325089,
  '1960': 1753947,
  '1970': 2207259,
  '1980': 2889964,
  '1990': 3294394,
  '2000': 4301261,
  '2010': 5029196},
 'Connecticut': {'1790': 237946,
  '1800': 251002,
  '1810': 262042,
  '1820': 275202,
  '1830': 297675,
  '1840': 309978,
  '1850': 370792,
  '1860': 460147,
  '1870': 537454,
  '1880': 622700,
  '1890': 746258,
  '1900': 908420,
  '1910': 1114756,
  '1920': 1380631,
  '1930': 1606903,
  '1940': 1709242,
  '1950': 2007280,
  '1960': 2535234,
  '1970': 3031709,
  '1980': 3107576,
  '1990': 3287116,
  '2000': 3405565,
  '2010': 3574097},
 'Delaware': {'1790': 59096,
  '1800': 64273,
  '1810': 72674,
  '1820': 72749,
  '1830': 76748,
  '1840': 78085,
  '1850': 91532,
  '1860': 112216,
  '1870': 125015,
  '1880': 146608,
  '1890': 168493,
  '1900': 184735,
  '1910': 202322,
  '1920': 223003,
  '1930': 238380,
  '1940': 266505,
  '1950': 318085,
  '1960': 446292,
  '1970': 548104,
  '1980': 594338,
  '1990': 666168,
  '2000': 783600,
  '2010': 897934},
 'District\xa0of\xa0Columbia': {'1790': 0,
  '1800': 8144,
  '1810': 15471,
  '1820': 23336,
  '1830': 30261,
  '1840': 33745,
  '1850': 51687,
  '1860': 75080,
  '1870': 131700,
  '1880': 177624,
  '1890': 230392,
  '1900': 278718,
  '1910': 331069,
  '1920': 437571,
  '1930': 486869,
  '1940': 663091,
  '1950': 802178,
  '1960': 763956,
  '1970': 756510,
  '1980': 638333,
  '1990': 606900,
  '2000': 572059,
  '2010': 601723},
 'Florida': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 34730,
  '1840': 54477,
  '1850': 87445,
  '1860': 140424,
  '1870': 187748,
  '1880': 269493,
  '1890': 391422,
  '1900': 528542,
  '1910': 752619,
  '1920': 968470,
  '1930': 1468211,
  '1940': 1897414,
  '1950': 2771305,
  '1960': 4951560,
  '1970': 6789443,
  '1980': 9746324,
  '1990': 12937926,
  '2000': 15982378,
  '2010': 18801310},
 'Georgia': {'1790': 82548,
  '1800': 162686,
  '1810': 251407,
  '1820': 340989,
  '1830': 516823,
  '1840': 691392,
  '1850': 906185,
  '1860': 1057286,
  '1870': 1184109,
  '1880': 1542180,
  '1890': 1837353,
  '1900': 2216331,
  '1910': 2609121,
  '1920': 2895832,
  '1930': 2908506,
  '1940': 3123723,
  '1950': 3444578,
  '1960': 3943116,
  '1970': 4589575,
  '1980': 5463105,
  '1990': 6478216,
  '2000': 8186453,
  '2010': 9687653},
 'Hawaii': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 0,
  '1900': 154001,
  '1910': 191909,
  '1920': 255912,
  '1930': 368336,
  '1940': 423330,
  '1950': 499794,
  '1960': 632772,
  '1970': 768561,
  '1980': 964691,
  '1990': 1108229,
  '2000': 1211537,
  '2010': 1360301},
 'Idaho': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 14999,
  '1880': 32610,
  '1890': 88548,
  '1900': 161772,
  '1910': 325594,
  '1920': 431866,
  '1930': 445032,
  '1940': 524873,
  '1950': 588637,
  '1960': 667191,
  '1970': 712567,
  '1980': 943935,
  '1990': 1006749,
  '2000': 1293953,
  '2010': 1567582},
 'Illinois': {'1790': 0,
  '1800': 2458,
  '1810': 12282,
  '1820': 55211,
  '1830': 157445,
  '1840': 476183,
  '1850': 851470,
  '1860': 1711951,
  '1870': 2539891,
  '1880': 3077871,
  '1890': 3826351,
  '1900': 4821550,
  '1910': 5638591,
  '1920': 6485280,
  '1930': 7630654,
  '1940': 7897241,
  '1950': 8712176,
  '1960': 10081158,
  '1970': 11113976,
  '1980': 11426518,
  '1990': 11430602,
  '2000': 12419293,
  '2010': 12830632},
 'Indiana': {'1790': 0,
  '1800': 2632,
  '1810': 24520,
  '1820': 147178,
  '1830': 343031,
  '1840': 685866,
  '1850': 988416,
  '1860': 1350428,
  '1870': 1680637,
  '1880': 1978301,
  '1890': 2192404,
  '1900': 2516462,
  '1910': 2700876,
  '1920': 2930390,
  '1930': 3238503,
  '1940': 3427796,
  '1950': 3934224,
  '1960': 4662498,
  '1970': 5193669,
  '1980': 5490224,
  '1990': 5544159,
  '2000': 6080485,
  '2010': 6483802},
 'Iowa': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 43112,
  '1850': 192214,
  '1860': 674913,
  '1870': 1194020,
  '1880': 1624615,
  '1890': 1912297,
  '1900': 2231853,
  '1910': 2224771,
  '1920': 2404021,
  '1930': 2470939,
  '1940': 2538268,
  '1950': 2621073,
  '1960': 2757537,
  '1970': 2824376,
  '1980': 2913808,
  '1990': 2776755,
  '2000': 2926324,
  '2010': 3046355},
 'Kansas': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 107206,
  '1870': 364399,
  '1880': 996096,
  '1890': 1428108,
  '1900': 1470495,
  '1910': 1690949,
  '1920': 1769257,
  '1930': 1880999,
  '1940': 1801028,
  '1950': 1905299,
  '1960': 2178611,
  '1970': 2246578,
  '1980': 2363679,
  '1990': 2477574,
  '2000': 2688418,
  '2010': 2853118},
 'Kentucky': {'1790': 73677,
  '1800': 220959,
  '1810': 406511,
  '1820': 564317,
  '1830': 687917,
  '1840': 779828,
  '1850': 982405,
  '1860': 1155684,
  '1870': 1321011,
  '1880': 1648690,
  '1890': 1858635,
  '1900': 2147174,
  '1910': 2289905,
  '1920': 2416630,
  '1930': 2614589,
  '1940': 2845627,
  '1950': 2944806,
  '1960': 3038156,
  '1970': 3218706,
  '1980': 3660777,
  '1990': 3685296,
  '2000': 4041769,
  '2010': 4339367},
 'Louisiana': {'1790': 0,
  '1800': 0,
  '1810': 76556,
  '1820': 153407,
  '1830': 215739,
  '1840': 352411,
  '1850': 517762,
  '1860': 708002,
  '1870': 726915,
  '1880': 939946,
  '1890': 1118587,
  '1900': 1381625,
  '1910': 1656388,
  '1920': 1798509,
  '1930': 2101593,
  '1940': 2363880,
  '1950': 2683516,
  '1960': 3257022,
  '1970': 3641306,
  '1980': 4205900,
  '1990': 4219973,
  '2000': 4468976,
  '2010': 4533372},
 'Maine': {'1790': 96540,
  '1800': 151719,
  '1810': 228705,
  '1820': 298335,
  '1830': 399455,
  '1840': 501793,
  '1850': 583169,
  '1860': 628279,
  '1870': 626915,
  '1880': 648936,
  '1890': 661086,
  '1900': 694466,
  '1910': 742371,
  '1920': 768014,
  '1930': 797423,
  '1940': 847226,
  '1950': 913774,
  '1960': 969265,
  '1970': 992048,
  '1980': 1124660,
  '1990': 1227928,
  '2000': 1274923,
  '2010': 1328361},
 'Maryland': {'1790': 319728,
  '1800': 341548,
  '1810': 380546,
  '1820': 407350,
  '1830': 447040,
  '1840': 470019,
  '1850': 583034,
  '1860': 687049,
  '1870': 780894,
  '1880': 934943,
  '1890': 1042390,
  '1900': 1188044,
  '1910': 1295346,
  '1920': 1449661,
  '1930': 1631526,
  '1940': 1821244,
  '1950': 2343001,
  '1960': 3100689,
  '1970': 3922399,
  '1980': 4216975,
  '1990': 4781468,
  '2000': 5296486,
  '2010': 5773552},
 'Massachusetts': {'1790': 378787,
  '1800': 422845,
  '1810': 472040,
  '1820': 523287,
  '1830': 610408,
  '1840': 737699,
  '1850': 994514,
  '1860': 1231066,
  '1870': 1457351,
  '1880': 1783085,
  '1890': 2238943,
  '1900': 2805346,
  '1910': 3366416,
  '1920': 3852356,
  '1930': 4249614,
  '1940': 4316721,
  '1950': 4690514,
  '1960': 5148578,
  '1970': 5689170,
  '1980': 5737037,
  '1990': 6016425,
  '2000': 6349097,
  '2010': 6547629},
 'Michigan': {'1790': 0,
  '1800': 3757,
  '1810': 4762,
  '1820': 7452,
  '1830': 28004,
  '1840': 212267,
  '1850': 397654,
  '1860': 749113,
  '1870': 1184059,
  '1880': 1636937,
  '1890': 2093889,
  '1900': 2420982,
  '1910': 2810173,
  '1920': 3668412,
  '1930': 4842325,
  '1940': 5256106,
  '1950': 6371766,
  '1960': 7823194,
  '1970': 8875083,
  '1980': 9262078,
  '1990': 9295297,
  '2000': 9938444,
  '2010': 9883640},
 'Minnesota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 6077,
  '1860': 172023,
  '1870': 439706,
  '1880': 780773,
  '1890': 1310283,
  '1900': 1751394,
  '1910': 2075708,
  '1920': 2387125,
  '1930': 2563953,
  '1940': 2792300,
  '1950': 2982483,
  '1960': 3413864,
  '1970': 3804971,
  '1980': 4075970,
  '1990': 4375099,
  '2000': 4919479,
  '2010': 5303925},
 'Mississippi': {'1790': 0,
  '1800': 7600,
  '1810': 31306,
  '1820': 75448,
  '1830': 136621,
  '1840': 375651,
  '1850': 606526,
  '1860': 791305,
  '1870': 827922,
  '1880': 1131597,
  '1890': 1289600,
  '1900': 1551270,
  '1910': 1797114,
  '1920': 1790618,
  '1930': 2009821,
  '1940': 2183796,
  '1950': 2178914,
  '1960': 2178141,
  '1970': 2216912,
  '1980': 2520638,
  '1990': 2573216,
  '2000': 2844658,
  '2010': 2967297},
 'Missouri': {'1790': 0,
  '1800': 0,
  '1810': 19783,
  '1820': 66586,
  '1830': 140455,
  '1840': 383702,
  '1850': 682044,
  '1860': 1182012,
  '1870': 1721295,
  '1880': 2168380,
  '1890': 2679184,
  '1900': 3106665,
  '1910': 3293335,
  '1920': 3404055,
  '1930': 3629367,
  '1940': 3784664,
  '1950': 3954653,
  '1960': 4319813,
  '1970': 4676501,
  '1980': 4916686,
  '1990': 5117073,
  '2000': 5595211,
  '2010': 5988927},
 'Montana': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 20595,
  '1880': 39159,
  '1890': 142924,
  '1900': 243329,
  '1910': 376053,
  '1920': 548889,
  '1930': 537606,
  '1940': 559456,
  '1950': 591024,
  '1960': 674767,
  '1970': 694409,
  '1980': 786690,
  '1990': 799065,
  '2000': 902195,
  '2010': 989415},
 'Nebraska': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 28841,
  '1870': 122993,
  '1880': 452402,
  '1890': 1062656,
  '1900': 1066300,
  '1910': 1192214,
  '1920': 1296372,
  '1930': 1377963,
  '1940': 1315834,
  '1950': 1325510,
  '1960': 1411330,
  '1970': 1483493,
  '1980': 1569825,
  '1990': 1578385,
  '2000': 1711263,
  '2010': 1826341},
 'Nevada': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 6857,
  '1870': 42491,
  '1880': 62266,
  '1890': 47355,
  '1900': 42335,
  '1910': 81875,
  '1920': 77407,
  '1930': 91058,
  '1940': 110247,
  '1950': 160083,
  '1960': 285278,
  '1970': 488738,
  '1980': 800493,
  '1990': 1201833,
  '2000': 1998257,
  '2010': 2700551},
 'New Hampshire': {'1790': 141885,
  '1800': 183858,
  '1810': 214360,
  '1820': 244161,
  '1830': 269328,
  '1840': 284574,
  '1850': 317976,
  '1860': 326073,
  '1870': 318300,
  '1880': 346991,
  '1890': 376530,
  '1900': 411588,
  '1910': 430572,
  '1920': 443083,
  '1930': 465293,
  '1940': 491524,
  '1950': 533242,
  '1960': 606921,
  '1970': 737681,
  '1980': 920610,
  '1990': 1109252,
  '2000': 1235786,
  '2010': 1316470},
 'New Jersey': {'1790': 184139,
  '1800': 211149,
  '1810': 245555,
  '1820': 277575,
  '1830': 320823,
  '1840': 373306,
  '1850': 489555,
  '1860': 672035,
  '1870': 906096,
  '1880': 1131116,
  '1890': 1444933,
  '1900': 1883669,
  '1910': 2537167,
  '1920': 3155900,
  '1930': 4041334,
  '1940': 4160165,
  '1950': 4835329,
  '1960': 6066782,
  '1970': 7168164,
  '1980': 7364823,
  '1990': 7730188,
  '2000': 8414350,
  '2010': 8791894},
 'New Mexico': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 61547,
  '1860': 87034,
  '1870': 91874,
  '1880': 119565,
  '1890': 160282,
  '1900': 195310,
  '1910': 327301,
  '1920': 360350,
  '1930': 423317,
  '1940': 531818,
  '1950': 681187,
  '1960': 951023,
  '1970': 1016000,
  '1980': 1302894,
  '1990': 1515069,
  '2000': 1819046,
  '2010': 2059179},
 'New York': {'1790': 340120,
  '1800': 586050,
  '1810': 959049,
  '1820': 1372812,
  '1830': 1918608,
  '1840': 2428921,
  '1850': 3097394,
  '1860': 3880735,
  '1870': 4382759,
  '1880': 5082871,
  '1890': 6003174,
  '1900': 7268894,
  '1910': 9113614,
  '1920': 10385227,
  '1930': 12588066,
  '1940': 13479142,
  '1950': 14830192,
  '1960': 16782304,
  '1970': 18236967,
  '1980': 17558072,
  '1990': 17990455,
  '2000': 18976457,
  '2010': 19378102},
 'North Carolina': {'1790': 393751,
  '1800': 478103,
  '1810': 556526,
  '1820': 638829,
  '1830': 737987,
  '1840': 753419,
  '1850': 869039,
  '1860': 992622,
  '1870': 1071361,
  '1880': 1399750,
  '1890': 1617947,
  '1900': 1893810,
  '1910': 2206287,
  '1920': 2559123,
  '1930': 3170276,
  '1940': 3571623,
  '1950': 4061929,
  '1960': 4556155,
  '1970': 5082059,
  '1980': 5881766,
  '1990': 6628637,
  '2000': 8049313,
  '2010': 9535483},
 'North Dakota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 2405,
  '1880': 36909,
  '1890': 190983,
  '1900': 319146,
  '1910': 577056,
  '1920': 646872,
  '1930': 680845,
  '1940': 641935,
  '1950': 619636,
  '1960': 632446,
  '1970': 617761,
  '1980': 652717,
  '1990': 638800,
  '2000': 642200,
  '2010': 672591},
 'Ohio': {'1790': 0,
  '1800': 42159,
  '1810': 230760,
  '1820': 581434,
  '1830': 937903,
  '1840': 1519467,
  '1850': 1980329,
  '1860': 2339511,
  '1870': 2665260,
  '1880': 3198062,
  '1890': 3672316,
  '1900': 4157545,
  '1910': 4767121,
  '1920': 5759394,
  '1930': 6646697,
  '1940': 6907612,
  '1950': 7946627,
  '1960': 9706397,
  '1970': 10652017,
  '1980': 10797630,
  '1990': 10847115,
  '2000': 11353140,
  '2010': 11536504},
 'Oklahoma': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 258657,
  '1900': 790391,
  '1910': 1657155,
  '1920': 2028283,
  '1930': 2396040,
  '1940': 2336434,
  '1950': 2233351,
  '1960': 2328284,
  '1970': 2559229,
  '1980': 3025290,
  '1990': 3145585,
  '2000': 3450654,
  '2010': 3751351},
 'Oregon': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 12093,
  '1860': 52465,
  '1870': 90923,
  '1880': 174768,
  '1890': 317704,
  '1900': 413536,
  '1910': 672765,
  '1920': 783389,
  '1930': 953786,
  '1940': 1089684,
  '1950': 1521341,
  '1960': 1768687,
  '1970': 2091385,
  '1980': 2633105,
  '1990': 2842321,
  '2000': 3421399,
  '2010': 3831074},
 'Pennsylvania': {'1790': 434373,
  '1800': 602545,
  '1810': 810091,
  '1820': 1049458,
  '1830': 1348233,
  '1840': 1724033,
  '1850': 2311786,
  '1860': 2906215,
  '1870': 3521951,
  '1880': 4282891,
  '1890': 5258014,
  '1900': 6302115,
  '1910': 7665111,
  '1920': 8720017,
  '1930': 9631350,
  '1940': 9900180,
  '1950': 10498012,
  '1960': 11319366,
  '1970': 11793909,
  '1980': 11863895,
  '1990': 11881643,
  '2000': 12281054,
  '2010': 12702379},
 'Rhode Island': {'1790': 68825,
  '1800': 69122,
  '1810': 76931,
  '1820': 83059,
  '1830': 97199,
  '1840': 108830,
  '1850': 147545,
  '1860': 174620,
  '1870': 217353,
  '1880': 276531,
  '1890': 345506,
  '1900': 428556,
  '1910': 542610,
  '1920': 604397,
  '1930': 687497,
  '1940': 713346,
  '1950': 791896,
  '1960': 859488,
  '1970': 946725,
  '1980': 947154,
  '1990': 1003464,
  '2000': 1048319,
  '2010': 1052567},
 'South Carolina': {'1790': 249073,
  '1800': 345591,
  '1810': 415115,
  '1820': 502741,
  '1830': 581185,
  '1840': 594398,
  '1850': 668507,
  '1860': 703708,
  '1870': 705606,
  '1880': 995577,
  '1890': 1151149,
  '1900': 1340316,
  '1910': 1515400,
  '1920': 1683724,
  '1930': 1738765,
  '1940': 1899804,
  '1950': 2117027,
  '1960': 2382594,
  '1970': 2590516,
  '1980': 3121820,
  '1990': 3486703,
  '2000': 4012012,
  '2010': 4625364},
 'South Dakota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 4837,
  '1870': 11776,
  '1880': 98268,
  '1890': 348600,
  '1900': 401570,
  '1910': 583888,
  '1920': 636547,
  '1930': 692849,
  '1940': 642961,
  '1950': 652740,
  '1960': 680514,
  '1970': 665507,
  '1980': 690768,
  '1990': 696004,
  '2000': 754844,
  '2010': 814180},
 'Tennessee': {'1790': 35691,
  '1800': 105602,
  '1810': 261727,
  '1820': 422813,
  '1830': 681904,
  '1840': 829210,
  '1850': 1002717,
  '1860': 1109801,
  '1870': 1258520,
  '1880': 1542359,
  '1890': 1767518,
  '1900': 2020616,
  '1910': 2184789,
  '1920': 2337885,
  '1930': 2616556,
  '1940': 2915841,
  '1950': 3291718,
  '1960': 3567089,
  '1970': 3923687,
  '1980': 4591120,
  '1990': 4877185,
  '2000': 5689283,
  '2010': 6346105},
 'Texas': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 212592,
  '1860': 604215,
  '1870': 818579,
  '1880': 1591749,
  '1890': 2235523,
  '1900': 3048710,
  '1910': 3896542,
  '1920': 4663228,
  '1930': 5824715,
  '1940': 6414824,
  '1950': 7711194,
  '1960': 9579677,
  '1970': 11196730,
  '1980': 14229191,
  '1990': 16986510,
  '2000': 20851820,
  '2010': 25145561},
 'United States': {'1790': 3929214,
  '1800': 5308483,
  '1810': 7239881,
  '1820': 9638453,
  '1830': 12860702,
  '1840': 17063353,
  '1850': 23191876,
  '1860': 31443321,
  '1870': 38558371,
  '1880': 50155783,
  '1890': 62947714,
  '1900': 75994575,
  '1910': 91972266,
  '1920': 105710620,
  '1930': 122775046,
  '1940': 131669275,
  '1950': 150697361,
  '1960': 179323175,
  '1970': 203211926,
  '1980': 226545805,
  '1990': 248709873,
  '2000': 281421906,
  '2010': 308745538},
 'Utah': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 11380,
  '1860': 40273,
  '1870': 86336,
  '1880': 143963,
  '1890': 210779,
  '1900': 276749,
  '1910': 373351,
  '1920': 449396,
  '1930': 507847,
  '1940': 550310,
  '1950': 688862,
  '1960': 890627,
  '1970': 1059273,
  '1980': 1461037,
  '1990': 1722850,
  '2000': 2233169,
  '2010': 2763885},
 'Vermont': {'1790': 85425,
  '1800': 154465,
  '1810': 217713,
  '1820': 235764,
  '1830': 280652,
  '1840': 291948,
  '1850': 314120,
  '1860': 315098,
  '1870': 330551,
  '1880': 332286,
  '1890': 332422,
  '1900': 343641,
  '1910': 355956,
  '1920': 352428,
  '1930': 359611,
  '1940': 359231,
  '1950': 377747,
  '1960': 389881,
  '1970': 444330,
  '1980': 511456,
  '1990': 562758,
  '2000': 608827,
  '2010': 625741},
 'Virginia': {'1790': 691937,
  '1800': 807557,
  '1810': 877683,
  '1820': 938261,
  '1830': 1044054,
  '1840': 1025227,
  '1850': 1119348,
  '1860': 1219630,
  '1870': 1225163,
  '1880': 1512565,
  '1890': 1655980,

## Use JSON to save and restore data

JSON (JavaScript Object Notation) is a simple data exchange format that can be used to serialize many data objects. To serialize an object means to convert it to a format that can be transmitted in a series, either to or from files or across a network.  This is particularly easy in python.  (See [pickle](https://docs.python.org/3/library/pickle.html) for an alternative means of 'serializing' python objects that supports a larger range of python objects but is not human readable (and not a universal format like json)

Here we'll use JSON to save our dictionary so that we can just load it from the file, if we need in the future.

In [14]:
filename = "historical_population.json"

# Open a file descriptor for writing, with the filename 'historical_population.json'.
# Convert our dictionary 'd' to JSON and output it to the file.
# Close the file.

# Your code here 
fd = open(filename,"w")
json.dump(d, fd, indent=4)
fd.close()

A convenient feature of JSON is that the resulting files are ASCII and thus simple to read (although they are larger than a corresponding binary format would be).

Let's use a shell command to look at the actual file.

In [15]:
!cat historical_population.json
# exclamation point here is a "magic" command that means 
# run line as shell command in terminal

{
    "Alabama": {
        "1790": 0,
        "1800": 1250,
        "1810": 9046,
        "1820": 127901,
        "1830": 309527,
        "1840": 590756,
        "1850": 771623,
        "1860": 964201,
        "1870": 996992,
        "1880": 1262505,
        "1890": 1513017,
        "1900": 1828697,
        "1910": 2138093,
        "1920": 2348174,
        "1930": 2646248,
        "1940": 2832961,
        "1950": 3061743,
        "1960": 3266740,
        "1970": 3444165,
        "1980": 3893888,
        "1990": 4040587,
        "2000": 4447100,
        "2010": 4779736
    },
    "Alaska": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 0,
        "1880": 0,
        "1890": 33426,
        "1900": 32052,
        "1910": 64356,
        "1920": 55036,
        "1930": 59278,
        "1940": 72524,
        "1950": 128643,
        "1960": 226167,
        "1970": 300382,
        "1980": 401851,
        "1990": 550043,
        "2000": 626932,
        "2010": 710231
    },
    "Arizona": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 9658,
        "1880": 40440,
        "1890": 88243,
        "1900": 122931,
        "1910": 204354,
        "1920": 334162,
        "1930": 435573,
        "1940": 499261,
        "1950": 749587,
        "1960": 1302161,
        "1970": 1770900,
        "1980": 2718215,
        "1990": 3665228,
        "2000": 5130632,
        "2010": 6392017
    },
    "Arkansas": {
        "1790": 0,
        "1800": 0,
        "1810": 1062,
        "1820": 14273,
        "1830": 30388,
        "1840": 97574,
        "1850": 209897,
        "1860": 435450,
        "1870": 484471,
        "1880": 802525,
        "1890": 1128211,
        "1900": 1311564,
        "1910": 1574449,
        "1920": 1752204,
        "1930": 1854482,
        "1940": 1949387,
        "1950": 1909511,
        "1960": 1786272,
        "1970": 1923295,
        "1980": 2286435,
        "1990": 2350725,
        "2000": 2673400,
        "2010": 2915918
    },
    "California": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 92597,
        "1860": 379994,
        "1870": 560247,
        "1880": 864694,
        "1890": 1213398,
        "1900": 1485053,
        "1910": 2377549,
        "1920": 3426861,
        "1930": 5677251,
        "1940": 6907387,
        "1950": 10586223,
        "1960": 15717204,
        "1970": 19953134,
        "1980": 23667902,
        "1990": 29760021,
        "2000": 33871648,
        "2010": 37253956
    },
    "Colorado": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 34277,
        "1870": 39864,
        "1880": 194327,
        "1890": 413249,
        "1900": 539700,
        "1910": 799024,
        "1920": 939629,
        "1930": 1035791,
        "1940": 1123296,
        "1950": 1325089,
        "1960": 1753947,
        "1970": 2207259,
        "1980": 2889964,
        "1990": 3294394,
        "2000": 4301261,
        "2010": 5029196
    },
    "Connecticut": {
        "1790": 237946,
        "1800": 251002,
        "1810": 262042,
        "1820": 275202,
        "1830": 297675,
        "1840": 309978,
        "1850": 370792,
        "1860": 460147,
        "1870": 537454,
        "1880": 622700,
        "1890": 746258,
        "1900": 908420,
        "1910": 1114756,
        "1920": 1380631,
        "1930": 1606903,
        "1940": 1709242,
        "1950": 2007280,
        "1960": 2535234,
        "1970": 3031709,
        "1980": 3107576,
        "1990": 3287116,
        "2000": 3405565,
        "2010": 3574097
    },
    "Delaware": {
        "1790": 59096,
        "1800": 64273,
        "1810": 72674,
        "1820": 72749,
        "1830": 76748,
        "1840": 78085,
        "1850": 91532,
        "1860": 112216,
        "1870": 125015,
        "1880": 146608,
        "1890": 168493,
        "1900": 184735,
        "1910": 202322,
        "1920": 223003,
        "1930": 238380,
        "1940": 266505,
        "1950": 318085,
        "1960": 446292,
        "1970": 548104,
        "1980": 594338,
        "1990": 666168,
        "2000": 783600,
        "2010": 897934
    },
    "District\u00a0of\u00a0Columbia": {
        "1790": 0,
        "1800": 8144,
        "1810": 15471,
        "1820": 23336,
        "1830": 30261,
        "1840": 33745,
        "1850": 51687,
        "1860": 75080,
        "1870": 131700,
        "1880": 177624,
        "1890": 230392,
        "1900": 278718,
        "1910": 331069,
        "1920": 437571,
        "1930": 486869,
        "1940": 663091,
        "1950": 802178,
        "1960": 763956,
        "1970": 756510,
        "1980": 638333,
        "1990": 606900,
        "2000": 572059,
        "2010": 601723
    },
    "Florida": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 34730,
        "1840": 54477,
        "1850": 87445,
        "1860": 140424,
        "1870": 187748,
        "1880": 269493,
        "1890": 391422,
        "1900": 528542,
        "1910": 752619,
        "1920": 968470,
        "1930": 1468211,
        "1940": 1897414,
        "1950": 2771305,
        "1960": 4951560,
        "1970": 6789443,
        "1980": 9746324,
        "1990": 12937926,
        "2000": 15982378,
        "2010": 18801310
    },
    "Georgia": {
        "1790": 82548,
        "1800": 162686,
        "1810": 251407,
        "1820": 340989,
        "1830": 516823,
        "1840": 691392,
        "1850": 906185,
        "1860": 1057286,
        "1870": 1184109,
        "1880": 1542180,
        "1890": 1837353,
        "1900": 2216331,
        "1910": 2609121,
        "1920": 2895832,
        "1930": 2908506,
        "1940": 3123723,
        "1950": 3444578,
        "1960": 3943116,
        "1970": 4589575,
        "1980": 5463105,
        "1990": 6478216,
        "2000": 8186453,
        "2010": 9687653
    },
    "Hawaii": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 0,
        "1880": 0,
        "1890": 0,
        "1900": 154001,
        "1910": 191909,
        "1920": 255912,
        "1930": 368336,
        "1940": 423330,
        "1950": 499794,
        "1960": 632772,
        "1970": 768561,
        "1980": 964691,
        "1990": 1108229,
        "2000": 1211537,
        "2010": 1360301
    },
    "Idaho": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 14999,
        "1880": 32610,
        "1890": 88548,
        "1900": 161772,
        "1910": 325594,
        "1920": 431866,
        "1930": 445032,
        "1940": 524873,
        "1950": 588637,
        "1960": 667191,
        "1970": 712567,
        "1980": 943935,
        "1990": 1006749,
        "2000": 1293953,
        "2010": 1567582
    },
    "Illinois": {
        "1790": 0,
        "1800": 2458,
        "1810": 12282,
        "1820": 55211,
        "1830": 157445,
        "1840": 476183,
        "1850": 851470,
        "1860": 1711951,
        "1870": 2539891,
        "1880": 3077871,
        "1890": 3826351,
        "1900": 4821550,
        "1910": 5638591,
        "1920": 6485280,
        "1930": 7630654,
        "1940": 7897241,
        "1950": 8712176,
        "1960": 10081158,
        "1970": 11113976,
        "1980": 11426518,
        "1990": 11430602,
        "2000": 12419293,
        "2010": 12830632
    },
    "Indiana": {
        "1790": 0,
        "1800": 2632,
        "1810": 24520,
        "1820": 147178,
        "1830": 343031,
        "1840": 685866,
        "1850": 988416,
        "1860": 1350428,
        "1870": 1680637,
        "1880": 1978301,
        "1890": 2192404,
        "1900": 2516462,
        "1910": 2700876,
        "1920": 2930390,
        "1930": 3238503,
        "1940": 3427796,
        "1950": 3934224,
        "1960": 4662498,
        "1970": 5193669,
        "1980": 5490224,
        "1990": 5544159,
        "2000": 6080485,
        "2010": 6483802
    },
    "Iowa": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 43112,
        "1850": 192214,
        "1860": 674913,
        "1870": 1194020,
        "1880": 1624615,
        "1890": 1912297,
        "1900": 2231853,
        "1910": 2224771,
        "1920": 2404021,
        "1930": 2470939,
        "1940": 2538268,
        "1950": 2621073,
        "1960": 2757537,
        "1970": 2824376,
        "1980": 2913808,
        "1990": 2776755,
        "2000": 2926324,
        "2010": 3046355
    },
    "Kansas": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 107206,
        "1870": 364399,
        "1880": 996096,
        "1890": 1428108,
        "1900": 1470495,
        "1910": 1690949,
        "1920": 1769257,
        "1930": 1880999,
        "1940": 1801028,
        "1950": 1905299,
        "1960": 2178611,
        "1970": 2246578,
        "1980": 2363679,
        "1990": 2477574,
        "2000": 2688418,
        "2010": 2853118
    },
    "Kentucky": {
        "1790": 73677,
        "1800": 220959,
        "1810": 406511,
        "1820": 564317,
        "1830": 687917,
        "1840": 779828,
        "1850": 982405,
        "1860": 1155684,
        "1870": 1321011,
        "1880": 1648690,
        "1890": 1858635,
        "1900": 2147174,
        "1910": 2289905,
        "1920": 2416630,
        "1930": 2614589,
        "1940": 2845627,
        "1950": 2944806,
        "1960": 3038156,
        "1970": 3218706,
        "1980": 3660777,
        "1990": 3685296,
        "2000": 4041769,
        "2010": 4339367
    },
    "Louisiana": {
        "1790": 0,
        "1800": 0,
        "1810": 76556,
        "1820": 153407,
        "1830": 215739,
        "1840": 352411,
        "1850": 517762,
        "1860": 708002,
        "1870": 726915,
        "1880": 939946,
        "1890": 1118587,
        "1900": 1381625,
        "1910": 1656388,
        "1920": 1798509,
        "1930": 2101593,
        "1940": 2363880,
        "1950": 2683516,
        "1960": 3257022,
        "1970": 3641306,
        "1980": 4205900,
        "1990": 4219973,
        "2000": 4468976,
        "2010": 4533372
    },
    "Maine": {
        "1790": 96540,
        "1800": 151719,
        "1810": 228705,
        "1820": 298335,
        "1830": 399455,
        "1840": 501793,
        "1850": 583169,
        "1860": 628279,
        "1870": 626915,
        "1880": 648936,
        "1890": 661086,
        "1900": 694466,
        "1910": 742371,
        "1920": 768014,
        "1930": 797423,
        "1940": 847226,
        "1950": 913774,
        "1960": 969265,
        "1970": 992048,
        "1980": 1124660,
        "1990": 1227928,
        "2000": 1274923,
        "2010": 1328361
    },
    "Maryland": {
        "1790": 319728,
        "1800": 341548,
        "1810": 380546,
        "1820": 407350,
        "1830": 447040,
        "1840": 470019,
        "1850": 583034,
        "1860": 687049,
        "1870": 780894,
        "1880": 934943,
        "1890": 1042390,
        "1900": 1188044,
        "1910": 1295346,
        "1920": 1449661,
        "1930": 1631526,
        "1940": 1821244,
        "1950": 2343001,
        "1960": 3100689,
        "1970": 3922399,
        "1980": 4216975,
        "1990": 4781468,
        "2000": 5296486,
        "2010": 5773552
    },
    "Massachusetts": {
        "1790": 378787,
        "1800": 422845,
        "1810": 472040,
        "1820": 523287,
        "1830": 610408,
        "1840": 737699,
        "1850": 994514,
        "1860": 1231066,
        "1870": 1457351,
        "1880": 1783085,
        "1890": 2238943,
        "1900": 2805346,
        "1910": 3366416,
        "1920": 3852356,
        "1930": 4249614,
        "1940": 4316721,
        "1950": 4690514,
        "1960": 5148578,
        "1970": 5689170,
        "1980": 5737037,
        "1990": 6016425,
        "2000": 6349097,
        "2010": 6547629
    },
    "Michigan": {
        "1790": 0,
        "1800": 3757,
        "1810": 4762,
        "1820": 7452,
        "1830": 28004,
        "1840": 212267,
        "1850": 397654,
        "1860": 749113,
        "1870": 1184059,
        "1880": 1636937,
        "1890": 2093889,
        "1900": 2420982,
        "1910": 2810173,
        "1920": 3668412,
        "1930": 4842325,
        "1940": 5256106,
        "1950": 6371766,
        "1960": 7823194,
        "1970": 8875083,
        "1980": 9262078,
        "1990": 9295297,
        "2000": 9938444,
        "2010": 9883640
    },
    "Minnesota": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 6077,
        "1860": 172023,
        "1870": 439706,
        "1880": 780773,
        "1890": 1310283,
        "1900": 1751394,
        "1910": 2075708,
        "1920": 2387125,
        "1930": 2563953,
        "1940": 2792300,
        "1950": 2982483,
        "1960": 3413864,
        "1970": 3804971,
        "1980": 4075970,
        "1990": 4375099,
        "2000": 4919479,
        "2010": 5303925
    },
    "Mississippi": {
        "1790": 0,
        "1800": 7600,
        "1810": 31306,
        "1820": 75448,
        "1830": 136621,
        "1840": 375651,
        "1850": 606526,
        "1860": 791305,
        "1870": 827922,
        "1880": 1131597,
        "1890": 1289600,
        "1900": 1551270,
        "1910": 1797114,
        "1920": 1790618,
        "1930": 2009821,
        "1940": 2183796,
        "1950": 2178914,
        "1960": 2178141,
        "1970": 2216912,
        "1980": 2520638,
        "1990": 2573216,
        "2000": 2844658,
        "2010": 2967297
    },
    "Missouri": {
        "1790": 0,
        "1800": 0,
        "1810": 19783,
        "1820": 66586,
        "1830": 140455,
        "1840": 383702,
        "1850": 682044,
        "1860": 1182012,
        "1870": 1721295,
        "1880": 2168380,
        "1890": 2679184,
        "1900": 3106665,
        "1910": 3293335,
        "1920": 3404055,
        "1930": 3629367,
        "1940": 3784664,
        "1950": 3954653,
        "1960": 4319813,
        "1970": 4676501,
        "1980": 4916686,
        "1990": 5117073,
        "2000": 5595211,
        "2010": 5988927
    },
    "Montana": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 20595,
        "1880": 39159,
        "1890": 142924,
        "1900": 243329,
        "1910": 376053,
        "1920": 548889,
        "1930": 537606,
        "1940": 559456,
        "1950": 591024,
        "1960": 674767,
        "1970": 694409,
        "1980": 786690,
        "1990": 799065,
        "2000": 902195,
        "2010": 989415
    },
    "Nebraska": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 28841,
        "1870": 122993,
        "1880": 452402,
        "1890": 1062656,
        "1900": 1066300,
        "1910": 1192214,
        "1920": 1296372,
        "1930": 1377963,
        "1940": 1315834,
        "1950": 1325510,
        "1960": 1411330,
        "1970": 1483493,
        "1980": 1569825,
        "1990": 1578385,
        "2000": 1711263,
        "2010": 1826341
    },
    "Nevada": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 6857,
        "1870": 42491,
        "1880": 62266,
        "1890": 47355,
        "1900": 42335,
        "1910": 81875,
        "1920": 77407,
        "1930": 91058,
        "1940": 110247,
        "1950": 160083,
        "1960": 285278,
        "1970": 488738,
        "1980": 800493,
        "1990": 1201833,
        "2000": 1998257,
        "2010": 2700551
    },
    "New Hampshire": {
        "1790": 141885,
        "1800": 183858,
        "1810": 214360,
        "1820": 244161,
        "1830": 269328,
        "1840": 284574,
        "1850": 317976,
        "1860": 326073,
        "1870": 318300,
        "1880": 346991,
        "1890": 376530,
        "1900": 411588,
        "1910": 430572,
        "1920": 443083,
        "1930": 465293,
        "1940": 491524,
        "1950": 533242,
        "1960": 606921,
        "1970": 737681,
        "1980": 920610,
        "1990": 1109252,
        "2000": 1235786,
        "2010": 1316470
    },
    "New Jersey": {
        "1790": 184139,
        "1800": 211149,
        "1810": 245555,
        "1820": 277575,
        "1830": 320823,
        "1840": 373306,
        "1850": 489555,
        "1860": 672035,
        "1870": 906096,
        "1880": 1131116,
        "1890": 1444933,
        "1900": 1883669,
        "1910": 2537167,
        "1920": 3155900,
        "1930": 4041334,
        "1940": 4160165,
        "1950": 4835329,
        "1960": 6066782,
        "1970": 7168164,
        "1980": 7364823,
        "1990": 7730188,
        "2000": 8414350,
        "2010": 8791894
    },
    "New Mexico": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 61547,
        "1860": 87034,
        "1870": 91874,
        "1880": 119565,
        "1890": 160282,
        "1900": 195310,
        "1910": 327301,
        "1920": 360350,
        "1930": 423317,
        "1940": 531818,
        "1950": 681187,
        "1960": 951023,
        "1970": 1016000,
        "1980": 1302894,
        "1990": 1515069,
        "2000": 1819046,
        "2010": 2059179
    },
    "New York": {
        "1790": 340120,
        "1800": 586050,
        "1810": 959049,
        "1820": 1372812,
        "1830": 1918608,
        "1840": 2428921,
        "1850": 3097394,
        "1860": 3880735,
        "1870": 4382759,
        "1880": 5082871,
        "1890": 6003174,
        "1900": 7268894,
        "1910": 9113614,
        "1920": 10385227,
        "1930": 12588066,
        "1940": 13479142,
        "1950": 14830192,
        "1960": 16782304,
        "1970": 18236967,
        "1980": 17558072,
        "1990": 17990455,
        "2000": 18976457,
        "2010": 19378102
    },
    "North Carolina": {
        "1790": 393751,
        "1800": 478103,
        "1810": 556526,
        "1820": 638829,
        "1830": 737987,
        "1840": 753419,
        "1850": 869039,
        "1860": 992622,
        "1870": 1071361,
        "1880": 1399750,
        "1890": 1617947,
        "1900": 1893810,
        "1910": 2206287,
        "1920": 2559123,
        "1930": 3170276,
        "1940": 3571623,
        "1950": 4061929,
        "1960": 4556155,
        "1970": 5082059,
        "1980": 5881766,
        "1990": 6628637,
        "2000": 8049313,
        "2010": 9535483
    },
    "North Dakota": {
        "1790": 0,
        "1800": 0,
        "1810": 0,
        "1820": 0,
        "1830": 0,
        "1840": 0,
        "1850": 0,
        "1860": 0,
        "1870": 2405,
        "1880": 36909,
        "1890": 190983,
        "1900": 319146,
        "1910": 577056,
        "1920": 646872,
        "1930": 680845,
        "1940": 641935,
        "1950": 619636,
        "1960": 632446,
        "1970": 617761,
        "1980": 652717,
        "1990": 638800,
        "2000": 642200,
        "2010": 672591
    },
    "Ohio": {
        "1790": 0,
        "1800": 42159,
        "1810": 230760,
        "1820": 581434,

It looks a lot like a python dictionary!

Let's demonstrate the use of JSON files by deleting d and then reloading it.

In [16]:
del d

In [17]:
d

NameError: name 'd' is not defined

In [18]:
# Now open the json file back up and save the results to d

# your code here
with open("historical_population.json", "r") as fd:
    d = json.load(fd)

In [19]:
d

{'Alabama': {'1790': 0,
  '1800': 1250,
  '1810': 9046,
  '1820': 127901,
  '1830': 309527,
  '1840': 590756,
  '1850': 771623,
  '1860': 964201,
  '1870': 996992,
  '1880': 1262505,
  '1890': 1513017,
  '1900': 1828697,
  '1910': 2138093,
  '1920': 2348174,
  '1930': 2646248,
  '1940': 2832961,
  '1950': 3061743,
  '1960': 3266740,
  '1970': 3444165,
  '1980': 3893888,
  '1990': 4040587,
  '2000': 4447100,
  '2010': 4779736},
 'Alaska': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 33426,
  '1900': 32052,
  '1910': 64356,
  '1920': 55036,
  '1930': 59278,
  '1940': 72524,
  '1950': 128643,
  '1960': 226167,
  '1970': 300382,
  '1980': 401851,
  '1990': 550043,
  '2000': 626932,
  '2010': 710231},
 'Arizona': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 9658,
  '1880': 40440,
  '1890': 88243,
  '1900': 122931,
  '1910': 204354,
  '1920': 334162,
  '1930': 435573,
  '1940': 499261,
  '1950': 749587,
  '1960': 1302161,
  '1970': 1770900,
  '1980': 2718215,
  '1990': 3665228,
  '2000': 5130632,
  '2010': 6392017},
 'Arkansas': {'1790': 0,
  '1800': 0,
  '1810': 1062,
  '1820': 14273,
  '1830': 30388,
  '1840': 97574,
  '1850': 209897,
  '1860': 435450,
  '1870': 484471,
  '1880': 802525,
  '1890': 1128211,
  '1900': 1311564,
  '1910': 1574449,
  '1920': 1752204,
  '1930': 1854482,
  '1940': 1949387,
  '1950': 1909511,
  '1960': 1786272,
  '1970': 1923295,
  '1980': 2286435,
  '1990': 2350725,
  '2000': 2673400,
  '2010': 2915918},
 'California': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 92597,
  '1860': 379994,
  '1870': 560247,
  '1880': 864694,
  '1890': 1213398,
  '1900': 1485053,
  '1910': 2377549,
  '1920': 3426861,
  '1930': 5677251,
  '1940': 6907387,
  '1950': 10586223,
  '1960': 15717204,
  '1970': 19953134,
  '1980': 23667902,
  '1990': 29760021,
  '2000': 33871648,
  '2010': 37253956},
 'Colorado': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 34277,
  '1870': 39864,
  '1880': 194327,
  '1890': 413249,
  '1900': 539700,
  '1910': 799024,
  '1920': 939629,
  '1930': 1035791,
  '1940': 1123296,
  '1950': 1325089,
  '1960': 1753947,
  '1970': 2207259,
  '1980': 2889964,
  '1990': 3294394,
  '2000': 4301261,
  '2010': 5029196},
 'Connecticut': {'1790': 237946,
  '1800': 251002,
  '1810': 262042,
  '1820': 275202,
  '1830': 297675,
  '1840': 309978,
  '1850': 370792,
  '1860': 460147,
  '1870': 537454,
  '1880': 622700,
  '1890': 746258,
  '1900': 908420,
  '1910': 1114756,
  '1920': 1380631,
  '1930': 1606903,
  '1940': 1709242,
  '1950': 2007280,
  '1960': 2535234,
  '1970': 3031709,
  '1980': 3107576,
  '1990': 3287116,
  '2000': 3405565,
  '2010': 3574097},
 'Delaware': {'1790': 59096,
  '1800': 64273,
  '1810': 72674,
  '1820': 72749,
  '1830': 76748,
  '1840': 78085,
  '1850': 91532,
  '1860': 112216,
  '1870': 125015,
  '1880': 146608,
  '1890': 168493,
  '1900': 184735,
  '1910': 202322,
  '1920': 223003,
  '1930': 238380,
  '1940': 266505,
  '1950': 318085,
  '1960': 446292,
  '1970': 548104,
  '1980': 594338,
  '1990': 666168,
  '2000': 783600,
  '2010': 897934},
 'District\xa0of\xa0Columbia': {'1790': 0,
  '1800': 8144,
  '1810': 15471,
  '1820': 23336,
  '1830': 30261,
  '1840': 33745,
  '1850': 51687,
  '1860': 75080,
  '1870': 131700,
  '1880': 177624,
  '1890': 230392,
  '1900': 278718,
  '1910': 331069,
  '1920': 437571,
  '1930': 486869,
  '1940': 663091,
  '1950': 802178,
  '1960': 763956,
  '1970': 756510,
  '1980': 638333,
  '1990': 606900,
  '2000': 572059,
  '2010': 601723},
 'Florida': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 34730,
  '1840': 54477,
  '1850': 87445,
  '1860': 140424,
  '1870': 187748,
  '1880': 269493,
  '1890': 391422,
  '1900': 528542,
  '1910': 752619,
  '1920': 968470,
  '1930': 1468211,
  '1940': 1897414,
  '1950': 2771305,
  '1960': 4951560,
  '1970': 6789443,
  '1980': 9746324,
  '1990': 12937926,
  '2000': 15982378,
  '2010': 18801310},
 'Georgia': {'1790': 82548,
  '1800': 162686,
  '1810': 251407,
  '1820': 340989,
  '1830': 516823,
  '1840': 691392,
  '1850': 906185,
  '1860': 1057286,
  '1870': 1184109,
  '1880': 1542180,
  '1890': 1837353,
  '1900': 2216331,
  '1910': 2609121,
  '1920': 2895832,
  '1930': 2908506,
  '1940': 3123723,
  '1950': 3444578,
  '1960': 3943116,
  '1970': 4589575,
  '1980': 5463105,
  '1990': 6478216,
  '2000': 8186453,
  '2010': 9687653},
 'Hawaii': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 0,
  '1900': 154001,
  '1910': 191909,
  '1920': 255912,
  '1930': 368336,
  '1940': 423330,
  '1950': 499794,
  '1960': 632772,
  '1970': 768561,
  '1980': 964691,
  '1990': 1108229,
  '2000': 1211537,
  '2010': 1360301},
 'Idaho': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 14999,
  '1880': 32610,
  '1890': 88548,
  '1900': 161772,
  '1910': 325594,
  '1920': 431866,
  '1930': 445032,
  '1940': 524873,
  '1950': 588637,
  '1960': 667191,
  '1970': 712567,
  '1980': 943935,
  '1990': 1006749,
  '2000': 1293953,
  '2010': 1567582},
 'Illinois': {'1790': 0,
  '1800': 2458,
  '1810': 12282,
  '1820': 55211,
  '1830': 157445,
  '1840': 476183,
  '1850': 851470,
  '1860': 1711951,
  '1870': 2539891,
  '1880': 3077871,
  '1890': 3826351,
  '1900': 4821550,
  '1910': 5638591,
  '1920': 6485280,
  '1930': 7630654,
  '1940': 7897241,
  '1950': 8712176,
  '1960': 10081158,
  '1970': 11113976,
  '1980': 11426518,
  '1990': 11430602,
  '2000': 12419293,
  '2010': 12830632},
 'Indiana': {'1790': 0,
  '1800': 2632,
  '1810': 24520,
  '1820': 147178,
  '1830': 343031,
  '1840': 685866,
  '1850': 988416,
  '1860': 1350428,
  '1870': 1680637,
  '1880': 1978301,
  '1890': 2192404,
  '1900': 2516462,
  '1910': 2700876,
  '1920': 2930390,
  '1930': 3238503,
  '1940': 3427796,
  '1950': 3934224,
  '1960': 4662498,
  '1970': 5193669,
  '1980': 5490224,
  '1990': 5544159,
  '2000': 6080485,
  '2010': 6483802},
 'Iowa': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 43112,
  '1850': 192214,
  '1860': 674913,
  '1870': 1194020,
  '1880': 1624615,
  '1890': 1912297,
  '1900': 2231853,
  '1910': 2224771,
  '1920': 2404021,
  '1930': 2470939,
  '1940': 2538268,
  '1950': 2621073,
  '1960': 2757537,
  '1970': 2824376,
  '1980': 2913808,
  '1990': 2776755,
  '2000': 2926324,
  '2010': 3046355},
 'Kansas': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 107206,
  '1870': 364399,
  '1880': 996096,
  '1890': 1428108,
  '1900': 1470495,
  '1910': 1690949,
  '1920': 1769257,
  '1930': 1880999,
  '1940': 1801028,
  '1950': 1905299,
  '1960': 2178611,
  '1970': 2246578,
  '1980': 2363679,
  '1990': 2477574,
  '2000': 2688418,
  '2010': 2853118},
 'Kentucky': {'1790': 73677,
  '1800': 220959,
  '1810': 406511,
  '1820': 564317,
  '1830': 687917,
  '1840': 779828,
  '1850': 982405,
  '1860': 1155684,
  '1870': 1321011,
  '1880': 1648690,
  '1890': 1858635,
  '1900': 2147174,
  '1910': 2289905,
  '1920': 2416630,
  '1930': 2614589,
  '1940': 2845627,
  '1950': 2944806,
  '1960': 3038156,
  '1970': 3218706,
  '1980': 3660777,
  '1990': 3685296,
  '2000': 4041769,
  '2010': 4339367},
 'Louisiana': {'1790': 0,
  '1800': 0,
  '1810': 76556,
  '1820': 153407,
  '1830': 215739,
  '1840': 352411,
  '1850': 517762,
  '1860': 708002,
  '1870': 726915,
  '1880': 939946,
  '1890': 1118587,
  '1900': 1381625,
  '1910': 1656388,
  '1920': 1798509,
  '1930': 2101593,
  '1940': 2363880,
  '1950': 2683516,
  '1960': 3257022,
  '1970': 3641306,
  '1980': 4205900,
  '1990': 4219973,
  '2000': 4468976,
  '2010': 4533372},
 'Maine': {'1790': 96540,
  '1800': 151719,
  '1810': 228705,
  '1820': 298335,
  '1830': 399455,
  '1840': 501793,
  '1850': 583169,
  '1860': 628279,
  '1870': 626915,
  '1880': 648936,
  '1890': 661086,
  '1900': 694466,
  '1910': 742371,
  '1920': 768014,
  '1930': 797423,
  '1940': 847226,
  '1950': 913774,
  '1960': 969265,
  '1970': 992048,
  '1980': 1124660,
  '1990': 1227928,
  '2000': 1274923,
  '2010': 1328361},
 'Maryland': {'1790': 319728,
  '1800': 341548,
  '1810': 380546,
  '1820': 407350,
  '1830': 447040,
  '1840': 470019,
  '1850': 583034,
  '1860': 687049,
  '1870': 780894,
  '1880': 934943,
  '1890': 1042390,
  '1900': 1188044,
  '1910': 1295346,
  '1920': 1449661,
  '1930': 1631526,
  '1940': 1821244,
  '1950': 2343001,
  '1960': 3100689,
  '1970': 3922399,
  '1980': 4216975,
  '1990': 4781468,
  '2000': 5296486,
  '2010': 5773552},
 'Massachusetts': {'1790': 378787,
  '1800': 422845,
  '1810': 472040,
  '1820': 523287,
  '1830': 610408,
  '1840': 737699,
  '1850': 994514,
  '1860': 1231066,
  '1870': 1457351,
  '1880': 1783085,
  '1890': 2238943,
  '1900': 2805346,
  '1910': 3366416,
  '1920': 3852356,
  '1930': 4249614,
  '1940': 4316721,
  '1950': 4690514,
  '1960': 5148578,
  '1970': 5689170,
  '1980': 5737037,
  '1990': 6016425,
  '2000': 6349097,
  '2010': 6547629},
 'Michigan': {'1790': 0,
  '1800': 3757,
  '1810': 4762,
  '1820': 7452,
  '1830': 28004,
  '1840': 212267,
  '1850': 397654,
  '1860': 749113,
  '1870': 1184059,
  '1880': 1636937,
  '1890': 2093889,
  '1900': 2420982,
  '1910': 2810173,
  '1920': 3668412,
  '1930': 4842325,
  '1940': 5256106,
  '1950': 6371766,
  '1960': 7823194,
  '1970': 8875083,
  '1980': 9262078,
  '1990': 9295297,
  '2000': 9938444,
  '2010': 9883640},
 'Minnesota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 6077,
  '1860': 172023,
  '1870': 439706,
  '1880': 780773,
  '1890': 1310283,
  '1900': 1751394,
  '1910': 2075708,
  '1920': 2387125,
  '1930': 2563953,
  '1940': 2792300,
  '1950': 2982483,
  '1960': 3413864,
  '1970': 3804971,
  '1980': 4075970,
  '1990': 4375099,
  '2000': 4919479,
  '2010': 5303925},
 'Mississippi': {'1790': 0,
  '1800': 7600,
  '1810': 31306,
  '1820': 75448,
  '1830': 136621,
  '1840': 375651,
  '1850': 606526,
  '1860': 791305,
  '1870': 827922,
  '1880': 1131597,
  '1890': 1289600,
  '1900': 1551270,
  '1910': 1797114,
  '1920': 1790618,
  '1930': 2009821,
  '1940': 2183796,
  '1950': 2178914,
  '1960': 2178141,
  '1970': 2216912,
  '1980': 2520638,
  '1990': 2573216,
  '2000': 2844658,
  '2010': 2967297},
 'Missouri': {'1790': 0,
  '1800': 0,
  '1810': 19783,
  '1820': 66586,
  '1830': 140455,
  '1840': 383702,
  '1850': 682044,
  '1860': 1182012,
  '1870': 1721295,
  '1880': 2168380,
  '1890': 2679184,
  '1900': 3106665,
  '1910': 3293335,
  '1920': 3404055,
  '1930': 3629367,
  '1940': 3784664,
  '1950': 3954653,
  '1960': 4319813,
  '1970': 4676501,
  '1980': 4916686,
  '1990': 5117073,
  '2000': 5595211,
  '2010': 5988927},
 'Montana': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 20595,
  '1880': 39159,
  '1890': 142924,
  '1900': 243329,
  '1910': 376053,
  '1920': 548889,
  '1930': 537606,
  '1940': 559456,
  '1950': 591024,
  '1960': 674767,
  '1970': 694409,
  '1980': 786690,
  '1990': 799065,
  '2000': 902195,
  '2010': 989415},
 'Nebraska': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 28841,
  '1870': 122993,
  '1880': 452402,
  '1890': 1062656,
  '1900': 1066300,
  '1910': 1192214,
  '1920': 1296372,
  '1930': 1377963,
  '1940': 1315834,
  '1950': 1325510,
  '1960': 1411330,
  '1970': 1483493,
  '1980': 1569825,
  '1990': 1578385,
  '2000': 1711263,
  '2010': 1826341},
 'Nevada': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 6857,
  '1870': 42491,
  '1880': 62266,
  '1890': 47355,
  '1900': 42335,
  '1910': 81875,
  '1920': 77407,
  '1930': 91058,
  '1940': 110247,
  '1950': 160083,
  '1960': 285278,
  '1970': 488738,
  '1980': 800493,
  '1990': 1201833,
  '2000': 1998257,
  '2010': 2700551},
 'New Hampshire': {'1790': 141885,
  '1800': 183858,
  '1810': 214360,
  '1820': 244161,
  '1830': 269328,
  '1840': 284574,
  '1850': 317976,
  '1860': 326073,
  '1870': 318300,
  '1880': 346991,
  '1890': 376530,
  '1900': 411588,
  '1910': 430572,
  '1920': 443083,
  '1930': 465293,
  '1940': 491524,
  '1950': 533242,
  '1960': 606921,
  '1970': 737681,
  '1980': 920610,
  '1990': 1109252,
  '2000': 1235786,
  '2010': 1316470},
 'New Jersey': {'1790': 184139,
  '1800': 211149,
  '1810': 245555,
  '1820': 277575,
  '1830': 320823,
  '1840': 373306,
  '1850': 489555,
  '1860': 672035,
  '1870': 906096,
  '1880': 1131116,
  '1890': 1444933,
  '1900': 1883669,
  '1910': 2537167,
  '1920': 3155900,
  '1930': 4041334,
  '1940': 4160165,
  '1950': 4835329,
  '1960': 6066782,
  '1970': 7168164,
  '1980': 7364823,
  '1990': 7730188,
  '2000': 8414350,
  '2010': 8791894},
 'New Mexico': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 61547,
  '1860': 87034,
  '1870': 91874,
  '1880': 119565,
  '1890': 160282,
  '1900': 195310,
  '1910': 327301,
  '1920': 360350,
  '1930': 423317,
  '1940': 531818,
  '1950': 681187,
  '1960': 951023,
  '1970': 1016000,
  '1980': 1302894,
  '1990': 1515069,
  '2000': 1819046,
  '2010': 2059179},
 'New York': {'1790': 340120,
  '1800': 586050,
  '1810': 959049,
  '1820': 1372812,
  '1830': 1918608,
  '1840': 2428921,
  '1850': 3097394,
  '1860': 3880735,
  '1870': 4382759,
  '1880': 5082871,
  '1890': 6003174,
  '1900': 7268894,
  '1910': 9113614,
  '1920': 10385227,
  '1930': 12588066,
  '1940': 13479142,
  '1950': 14830192,
  '1960': 16782304,
  '1970': 18236967,
  '1980': 17558072,
  '1990': 17990455,
  '2000': 18976457,
  '2010': 19378102},
 'North Carolina': {'1790': 393751,
  '1800': 478103,
  '1810': 556526,
  '1820': 638829,
  '1830': 737987,
  '1840': 753419,
  '1850': 869039,
  '1860': 992622,
  '1870': 1071361,
  '1880': 1399750,
  '1890': 1617947,
  '1900': 1893810,
  '1910': 2206287,
  '1920': 2559123,
  '1930': 3170276,
  '1940': 3571623,
  '1950': 4061929,
  '1960': 4556155,
  '1970': 5082059,
  '1980': 5881766,
  '1990': 6628637,
  '2000': 8049313,
  '2010': 9535483},
 'North Dakota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 2405,
  '1880': 36909,
  '1890': 190983,
  '1900': 319146,
  '1910': 577056,
  '1920': 646872,
  '1930': 680845,
  '1940': 641935,
  '1950': 619636,
  '1960': 632446,
  '1970': 617761,
  '1980': 652717,
  '1990': 638800,
  '2000': 642200,
  '2010': 672591},
 'Ohio': {'1790': 0,
  '1800': 42159,
  '1810': 230760,
  '1820': 581434,
  '1830': 937903,
  '1840': 1519467,
  '1850': 1980329,
  '1860': 2339511,
  '1870': 2665260,
  '1880': 3198062,
  '1890': 3672316,
  '1900': 4157545,
  '1910': 4767121,
  '1920': 5759394,
  '1930': 6646697,
  '1940': 6907612,
  '1950': 7946627,
  '1960': 9706397,
  '1970': 10652017,
  '1980': 10797630,
  '1990': 10847115,
  '2000': 11353140,
  '2010': 11536504},
 'Oklahoma': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 0,
  '1870': 0,
  '1880': 0,
  '1890': 258657,
  '1900': 790391,
  '1910': 1657155,
  '1920': 2028283,
  '1930': 2396040,
  '1940': 2336434,
  '1950': 2233351,
  '1960': 2328284,
  '1970': 2559229,
  '1980': 3025290,
  '1990': 3145585,
  '2000': 3450654,
  '2010': 3751351},
 'Oregon': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 12093,
  '1860': 52465,
  '1870': 90923,
  '1880': 174768,
  '1890': 317704,
  '1900': 413536,
  '1910': 672765,
  '1920': 783389,
  '1930': 953786,
  '1940': 1089684,
  '1950': 1521341,
  '1960': 1768687,
  '1970': 2091385,
  '1980': 2633105,
  '1990': 2842321,
  '2000': 3421399,
  '2010': 3831074},
 'Pennsylvania': {'1790': 434373,
  '1800': 602545,
  '1810': 810091,
  '1820': 1049458,
  '1830': 1348233,
  '1840': 1724033,
  '1850': 2311786,
  '1860': 2906215,
  '1870': 3521951,
  '1880': 4282891,
  '1890': 5258014,
  '1900': 6302115,
  '1910': 7665111,
  '1920': 8720017,
  '1930': 9631350,
  '1940': 9900180,
  '1950': 10498012,
  '1960': 11319366,
  '1970': 11793909,
  '1980': 11863895,
  '1990': 11881643,
  '2000': 12281054,
  '2010': 12702379},
 'Rhode Island': {'1790': 68825,
  '1800': 69122,
  '1810': 76931,
  '1820': 83059,
  '1830': 97199,
  '1840': 108830,
  '1850': 147545,
  '1860': 174620,
  '1870': 217353,
  '1880': 276531,
  '1890': 345506,
  '1900': 428556,
  '1910': 542610,
  '1920': 604397,
  '1930': 687497,
  '1940': 713346,
  '1950': 791896,
  '1960': 859488,
  '1970': 946725,
  '1980': 947154,
  '1990': 1003464,
  '2000': 1048319,
  '2010': 1052567},
 'South Carolina': {'1790': 249073,
  '1800': 345591,
  '1810': 415115,
  '1820': 502741,
  '1830': 581185,
  '1840': 594398,
  '1850': 668507,
  '1860': 703708,
  '1870': 705606,
  '1880': 995577,
  '1890': 1151149,
  '1900': 1340316,
  '1910': 1515400,
  '1920': 1683724,
  '1930': 1738765,
  '1940': 1899804,
  '1950': 2117027,
  '1960': 2382594,
  '1970': 2590516,
  '1980': 3121820,
  '1990': 3486703,
  '2000': 4012012,
  '2010': 4625364},
 'South Dakota': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 0,
  '1860': 4837,
  '1870': 11776,
  '1880': 98268,
  '1890': 348600,
  '1900': 401570,
  '1910': 583888,
  '1920': 636547,
  '1930': 692849,
  '1940': 642961,
  '1950': 652740,
  '1960': 680514,
  '1970': 665507,
  '1980': 690768,
  '1990': 696004,
  '2000': 754844,
  '2010': 814180},
 'Tennessee': {'1790': 35691,
  '1800': 105602,
  '1810': 261727,
  '1820': 422813,
  '1830': 681904,
  '1840': 829210,
  '1850': 1002717,
  '1860': 1109801,
  '1870': 1258520,
  '1880': 1542359,
  '1890': 1767518,
  '1900': 2020616,
  '1910': 2184789,
  '1920': 2337885,
  '1930': 2616556,
  '1940': 2915841,
  '1950': 3291718,
  '1960': 3567089,
  '1970': 3923687,
  '1980': 4591120,
  '1990': 4877185,
  '2000': 5689283,
  '2010': 6346105},
 'Texas': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 212592,
  '1860': 604215,
  '1870': 818579,
  '1880': 1591749,
  '1890': 2235523,
  '1900': 3048710,
  '1910': 3896542,
  '1920': 4663228,
  '1930': 5824715,
  '1940': 6414824,
  '1950': 7711194,
  '1960': 9579677,
  '1970': 11196730,
  '1980': 14229191,
  '1990': 16986510,
  '2000': 20851820,
  '2010': 25145561},
 'United States': {'1790': 3929214,
  '1800': 5308483,
  '1810': 7239881,
  '1820': 9638453,
  '1830': 12860702,
  '1840': 17063353,
  '1850': 23191876,
  '1860': 31443321,
  '1870': 38558371,
  '1880': 50155783,
  '1890': 62947714,
  '1900': 75994575,
  '1910': 91972266,
  '1920': 105710620,
  '1930': 122775046,
  '1940': 131669275,
  '1950': 150697361,
  '1960': 179323175,
  '1970': 203211926,
  '1980': 226545805,
  '1990': 248709873,
  '2000': 281421906,
  '2010': 308745538},
 'Utah': {'1790': 0,
  '1800': 0,
  '1810': 0,
  '1820': 0,
  '1830': 0,
  '1840': 0,
  '1850': 11380,
  '1860': 40273,
  '1870': 86336,
  '1880': 143963,
  '1890': 210779,
  '1900': 276749,
  '1910': 373351,
  '1920': 449396,
  '1930': 507847,
  '1940': 550310,
  '1950': 688862,
  '1960': 890627,
  '1970': 1059273,
  '1980': 1461037,
  '1990': 1722850,
  '2000': 2233169,
  '2010': 2763885},
 'Vermont': {'1790': 85425,
  '1800': 154465,
  '1810': 217713,
  '1820': 235764,
  '1830': 280652,
  '1840': 291948,
  '1850': 314120,
  '1860': 315098,
  '1870': 330551,
  '1880': 332286,
  '1890': 332422,
  '1900': 343641,
  '1910': 355956,
  '1920': 352428,
  '1930': 359611,
  '1940': 359231,
  '1950': 377747,
  '1960': 389881,
  '1970': 444330,
  '1980': 511456,
  '1990': 562758,
  '2000': 608827,
  '2010': 625741},
 'Virginia': {'1790': 691937,
  '1800': 807557,
  '1810': 877683,
  '1820': 938261,
  '1830': 1044054,
  '1840': 1025227,
  '1850': 1119348,
  '1860': 1219630,
  '1870': 1225163,
  '1880': 1512565,
  '1890': 1655980,

We successfully restored the dictionary from its JSON file!

## Generate the dataframe

Now that we have the dictionary, it's straightfoward to generate a pandas dataframe from it.

In [20]:
# Generate the dataframe from the dictionary.
df = pd.DataFrame.from_dict(d,orient='index')

# Drop unneeded rows.
df = df.drop(["United States"])  

# Sort the columns in increasing (alphabetical) order.
df = df.reindex_axis(sorted(df.columns), axis=1)

df.head()

            1790  1800  1810    1820    1830    1840    1850    1860    1870     1880     1890     1900     1910     1920     1930     1940      1950      1960      1970      1980      1990      2000      2010
Alabama        0  1250  9046  127901  309527  590756  771623  964201  996992  1262505  1513017  1828697  2138093  2348174  2646248  2832961   3061743   3266740   3444165   3893888   4040587   4447100   4779736
Alaska         0     0     0       0       0       0       0       0       0        0    33426    32052    64356    55036    59278    72524    128643    226167    300382    401851    550043    626932    710231
Arizona        0     0     0       0       0       0       0       0    9658    40440    88243   122931   204354   334162   435573   499261    749587   1302161   1770900   2718215   3665228   5130632   6392017
Arkansas       0     0  1062   14273   30388   97574  209897  435450  484471   802525  1128211  1311564  1574449  1752204  1854482  1949387   1909511   1786272   1923295   2286435   2350725   2673400   2915918
California     0     0     0       0       0       0   92597  379994  560247   864694  1213398  1485053  2377549  3426861  5677251  6907387  10586223  15717204  19953134  23667902  29760021  33871648  37253956

## Alternative to saving JSON – save dataframe object as csv

In [21]:
df.to_csv("historical_population.csv")

In [22]:
!cat historical_population.csv

,1790,1800,1810,1820,1830,1840,1850,1860,1870,1880,1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010
Alabama,0,1250,9046,127901,309527,590756,771623,964201,996992,1262505,1513017,1828697,2138093,2348174,2646248,2832961,3061743,3266740,3444165,3893888,4040587,4447100,4779736
Alaska,0,0,0,0,0,0,0,0,0,0,33426,32052,64356,55036,59278,72524,128643,226167,300382,401851,550043,626932,710231
Arizona,0,0,0,0,0,0,0,0,9658,40440,88243,122931,204354,334162,435573,499261,749587,1302161,1770900,2718215,3665228,5130632,6392017
Arkansas,0,0,1062,14273,30388,97574,209897,435450,484471,802525,1128211,1311564,1574449,1752204,1854482,1949387,1909511,1786272,1923295,2286435,2350725,2673400,2915918
California,0,0,0,0,0,0,92597,379994,560247,864694,1213398,1485053,2377549,3426861,5677251,6907387,10586223,15717204,19953134,23667902,29760021,33871648,37253956
Colorado,0,0,0,0,0,0,0,34277,39864,194327,413249,539700,799024,939629,1035791,1123296,1325089,1753947,2207259,2889964,3294394,4301261,5029196
Connecticut,237946,251002,262042,275202,297675,309978,370792,460147,537454,622700,746258,908420,1114756,1380631,1606903,1709242,2007280,2535234,3031709,3107576,3287116,3405565,3574097
Delaware,59096,64273,72674,72749,76748,78085,91532,112216,125015,146608,168493,184735,202322,223003,238380,266505,318085,446292,548104,594338,666168,783600,897934
District of Columbia,0,8144,15471,23336,30261,33745,51687,75080,131700,177624,230392,278718,331069,437571,486869,663091,802178,763956,756510,638333,606900,572059,601723
Florida,0,0,0,0,34730,54477,87445,140424,187748,269493,391422,528542,752619,968470,1468211,1897414,2771305,4951560,6789443,9746324,12937926,15982378,18801310
Georgia,82548,162686,251407,340989,516823,691392,906185,1057286,1184109,1542180,1837353,2216331,2609121,2895832,2908506,3123723,3444578,3943116,4589575,5463105,6478216,8186453,9687653
Hawaii,0,0,0,0,0,0,0,0,0,0,0,154001,191909,255912,368336,423330,499794,632772,768561,964691,1108229,1211537,1360301
Idaho,0,0,0,0,0,0,0,0,14999,32610,88548,161772,325594,431866,445032,524873,588637,667191,712567,943935,1006749,1293953,1567582
Illinois,0,2458,12282,55211,157445,476183,851470,1711951,2539891,3077871,3826351,4821550,5638591,6485280,7630654,7897241,8712176,10081158,11113976,11426518,11430602,12419293,12830632
Indiana,0,2632,24520,147178,343031,685866,988416,1350428,1680637,1978301,2192404,2516462,2700876,2930390,3238503,3427796,3934224,4662498,5193669,5490224,5544159,6080485,6483802
Iowa,0,0,0,0,0,43112,192214,674913,1194020,1624615,1912297,2231853,2224771,2404021,2470939,2538268,2621073,2757537,2824376,2913808,2776755,2926324,3046355
Kansas,0,0,0,0,0,0,0,107206,364399,996096,1428108,1470495,1690949,1769257,1880999,1801028,1905299,2178611,2246578,2363679,2477574,2688418,2853118
Kentucky,73677,220959,406511,564317,687917,779828,982405,1155684,1321011,1648690,1858635,2147174,2289905,2416630,2614589,2845627,2944806,3038156,3218706,3660777,3685296,4041769,4339367
Louisiana,0,0,76556,153407,215739,352411,517762,708002,726915,939946,1118587,1381625,1656388,1798509,2101593,2363880,2683516,3257022,3641306,4205900,4219973,4468976,4533372
Maine,96540,151719,228705,298335,399455,501793,583169,628279,626915,648936,661086,694466,742371,768014,797423,847226,913774,969265,992048,1124660,1227928,1274923,1328361
Maryland,319728,341548,380546,407350,447040,470019,583034,687049,780894,934943,1042390,1188044,1295346,1449661,1631526,1821244,2343001,3100689,3922399,4216975,4781468,5296486,5773552
Massachusetts,378787,422845,472040,523287,610408,737699,994514,1231066,1457351,1783085,2238943,2805346,3366416,3852356,4249614,4316721,4690514,5148578,5689170,5737037,6016425,6349097,6547629
Michigan,0,3757,4762,7452,28004,212267,397654,749113,1184059,1636937,2093889,2420982,2810173,3668412,4842325,5256106,6371766,7823194,8875083,9262078,9295297,9938444,9883640
Minnesota,0,0,0,0,0,0,6077,172023,439706,780773,1310283,1751394,2075708,2387125,2563953,2792300,2982483,3413864,3804971,4075970,4375099,4919479,5303925
Mississippi,0,7600,31306,75448,136621,375651,606526,791305,827922,1131597,1289600,1551270,1797114,1790618,2009821,2183796,2178914,2178141,2216912,2520638,2573216,2844658,2967297
Missouri,0,0,19783,66586,140455,383702,682044,1182012,1721295,2168380,2679184,3106665,3293335,3404055,3629367,3784664,3954653,4319813,4676501,4916686,5117073,5595211,5988927
Montana,0,0,0,0,0,0,0,0,20595,39159,142924,243329,376053,548889,537606,559456,591024,674767,694409,786690,799065,902195,989415
Nebraska,0,0,0,0,0,0,0,28841,122993,452402,1062656,1066300,1192214,1296372,1377963,1315834,1325510,1411330,1483493,1569825,1578385,1711263,1826341
Nevada,0,0,0,0,0,0,0,6857,42491,62266,47355,42335,81875,77407,91058,110247,160083,285278,488738,800493,1201833,1998257,2700551
New Hampshire,141885,183858,214360,244161,269328,284574,317976,326073,318300,346991,376530,411588,430572,443083,465293,491524,533242,606921,737681,920610,1109252,1235786,1316470
New Jersey,184139,211149,245555,277575,320823,373306,489555,672035,906096,1131116,1444933,1883669,2537167,3155900,4041334,4160165,4835329,6066782,7168164,7364823,7730188,8414350,8791894
New Mexico,0,0,0,0,0,0,61547,87034,91874,119565,160282,195310,327301,360350,423317,531818,681187,951023,1016000,1302894,1515069,1819046,2059179
New York,340120,586050,959049,1372812,1918608,2428921,3097394,3880735,4382759,5082871,6003174,7268894,9113614,10385227,12588066,13479142,14830192,16782304,18236967,17558072,17990455,18976457,19378102
North Carolina,393751,478103,556526,638829,737987,753419,869039,992622,1071361,1399750,1617947,1893810,2206287,2559123,3170276,3571623,4061929,4556155,5082059,5881766,6628637,8049313,9535483
North Dakota,0,0,0,0,0,0,0,0,2405,36909,190983,319146,577056,646872,680845,641935,619636,632446,617761,652717,638800,642200,672591
Ohio,0,42159,230760,581434,937903,1519467,1980329,2339511,2665260,3198062,3672316,4157545,4767121,5759394,6646697,6907612,7946627,9706397,10652017,10797630,10847115,11353140,11536504
Oklahoma,0,0,0,0,0,0,0,0,0,0,258657,790391,1657155,2028283,2396040,2336434,2233351,2328284,2559229,3025290,3145585,3450654,3751351
Oregon,0,0,0,0,0,0,12093,52465,90923,174768,317704,413536,672765,783389,953786,1089684,1521341,1768687,2091385,2633105,2842321,3421399,3831074
Pennsylvania,434373,602545,810091,1049458,1348233,1724033,2311786,2906215,3521951,4282891,5258014,6302115,7665111,8720017,9631350,9900180,10498012,11319366,11793909,11863895,11881643,12281054,12702379
Rhode Island,68825,69122,76931,83059,97199,108830,147545,174620,217353,276531,345506,428556,542610,604397,687497,713346,791896,859488,946725,947154,1003464,1048319,1052567
South Carolina,249073,345591,415115,502741,581185,594398,668507,703708,705606,995577,1151149,1340316,1515400,1683724,1738765,1899804,2117027,2382594,2590516,3121820,3486703,4012012,4625364
South Dakota,0,0,0,0,0,0,0,4837,11776,98268,348600,401570,583888,636547,692849,642961,652740,680514,665507,690768,696004,754844,814180
Tennessee,35691,105602,261727,422813,681904,829210,1002717,1109801,1258520,1542359,1767518,2020616,2184789,2337885,2616556,2915841,3291718,3567089,3923687,4591120,4877185,5689283,6346105
Texas,0,0,0,0,0,0,212592,604215,818579,1591749,2235523,3048710,3896542,4663228,5824715,6414824,7711194,9579677,11196730,14229191,16986510,20851820,25145561
Utah,0,0,0,0,0,0,11380,40273,86336,143963,210779,276749,373351,449396,507847,550310,688862,890627,1059273,1461037,1722850,2233169,2763885
Vermont,85425,154465,217713,235764,280652,291948,314120,315098,330551,332286,332422,343641,355956,352428,359611,359231,377747,389881,444330,511456,562758,608827,625741
Virginia,691937,807557,877683,938261,1044054,1025227,1119348,1219630,1225163,1512565,1655980,1854184,2061612,2309187,2421851,2677773,3318680,3966949,4648494,5346818,6187358,7078515,8001024
Washington,0,0,0,0,0,0,1201,11594,23955,75116,357232,518103,1141990,1356621,1563396,1736191,2378963,2853214,3409169,4132156,4866692,5894121,6724540
West Virginia,55873,78592,105469,136808,176924,224537,302313,376688,442014,618457,762794,958800,1221119,1463701,1729205,1901974,2005552,1860421,1744237,1949644,1793477,1808344,1852994
Wisconsin,0,0,0,1444,3635,30945,305391,775881,1054670,1315497,1693330,2069042,2333860,2632067,2939006,3137587,3434575,3951777,4417731,4705767,4891769,5363675,5686986
Wyoming,0,0,0,0,0,0,0,0,9118,20789,60705,92531,145965,194402,225565,250742,290529,330066,332416,469557,453588,493782,563626

In [23]:
df.from_csv("historical_population.csv").head()

            1790  1800  1810    1820    1830    1840    1850    1860    1870     1880     1890     1900     1910     1920     1930     1940      1950      1960      1970      1980      1990      2000      2010
Alabama        0  1250  9046  127901  309527  590756  771623  964201  996992  1262505  1513017  1828697  2138093  2348174  2646248  2832961   3061743   3266740   3444165   3893888   4040587   4447100   4779736
Alaska         0     0     0       0       0       0       0       0       0        0    33426    32052    64356    55036    59278    72524    128643    226167    300382    401851    550043    626932    710231
Arizona        0     0     0       0       0       0       0       0    9658    40440    88243   122931   204354   334162   435573   499261    749587   1302161   1770900   2718215   3665228   5130632   6392017
Arkansas       0     0  1062   14273   30388   97574  209897  435450  484471   802525  1128211  1311564  1574449  1752204  1854482  1949387   1909511   1786272   1923295   2286435   2350725   2673400   2915918
California     0     0     0       0       0       0   92597  379994  560247   864694  1213398  1485053  2377549  3426861  5677251  6907387  10586223  15717204  19953134  23667902  29760021  33871648  37253956

Exporting as csv is another useful method for saving a data frame offline you can easily jump back to your dataset without needed to re-scrape from Wikipedia. Note however that when we export as csv, no metadata about the data frame is saved which can cause subtle differences on re-import in the datatypes of your columns and which column is used as the index.

## Download, extract, and parse another webpage

Now that we have regenerated the dictionary and dataframe from last section, let's demonstrate a slightly different approach to downloading, extracting, and parsing.   This time we will look at a webpage of the US states by income.

We'll re-use our previous function to download and parse the page.

In [24]:
soup = get_parsed_html("https://en.wikipedia.org/wiki/List_of_U.S._states_by_income")
soup.find('title').text

'List of U.S. states by income - Wikipedia'

In [25]:
tables = soup.find_all("table",attrs={"class":"wikitable"})
# This says return a list of all table objects that include 
# the css class “wikitable” within the soup object.  
len(tables)

2

This page has two wikitables, and we are interested in the second one, which looks like this.

In [26]:
# Let's render the second table as HTML
from IPython.core.display import display, HTML
display(HTML(tables[1].prettify()))

## Convert the html table directly into a pandas dataframe

For well formatted HTML tables the pandas read_html method works like a charm, and it can be much easier than building a dataframe row by row. 

With the read_html method, we can specify which row has the column names and which column is the index.  We'll start by using the first row and first column.

In [27]:
df1 = pd.read_html(tables[1].prettify(),header=0, index_col=0)[0]

In [28]:
df1.head()

                     State Per capita  income Median  household  income Median  family  income  Population  Number of  households  Number of  families
Rank
NaN   District of Columbia            $45,877                   $71,648                $84,094      658893                 277378               117864
 1.0           Connecticut            $39,373                   $70,048                $88,819     3596677                1355817               887263
 2.0            New Jersey            $37,288                   $69,160                $87,951     8938175                2549336              1610581
 3.0         Massachusetts            $36,593                   $71,919                $88,419     6938608                3194844              2203675
 4.0              Maryland            $36,338                   $73,971                $89,678     5976407                2165438              1445972

## Clean up the dataframe

There are a few things we should clean up before proceeding. First let's set the index to be the'State' column.

In [29]:
df1 = df1.set_index('State')

Note that by overwriting the index, we’re discarding the 'Rank' column.

In [30]:
df1.head()

                     Per capita  income Median  household  income Median  family  income  Population  Number of  households  Number of  families
State
District of Columbia            $45,877                   $71,648                $84,094      658893                 277378               117864
Connecticut                     $39,373                   $70,048                $88,819     3596677                1355817               887263
New Jersey                      $37,288                   $69,160                $87,951     8938175                2549336              1610581
Massachusetts                   $36,593                   $71,919                $88,419     6938608                3194844              2203675
Maryland                        $36,338                   $73,971                $89,678     5976407                2165438              1445972

Next, let's drop the 'United States' row -- but keep your eye on the District of Columbia and Puerto Rico rows.

In [31]:
df1 = df1.drop(["United States"])

Also, the column names have one or more spaces embedded in them.  That can make the columns difficult to select.  Fortunately, a pandas dataframe allows easy access to the column names as follows:

In [32]:
df1.columns.values

array(['Per capita  income', 'Median  household  income',
       'Median  family  income', 'Population', 'Number of  households',
       'Number of  families'], dtype=object)

Notice that this is a numpy array of type 'object' with a list of column names.
We can write a quick reformatting function and apply it to all the column names.  

Here we use both 'strip' which is a built_in method of string objects and the 're' (regular expression) substitution method.  Regular expressions are a powerful, concise way of representing an enormous range of string transformations.  

To learn more about regular expresions in python, see:
https://docs.python.org/3/library/re.html

In [34]:
import re
def clean_column_name(s):
    """This removes any leading or trailing spaces and
    replaces multiple embedded spaces with a single
    underscore character
    
    'Per capita  income' -> 'Per_capita_income'
    """
    # Your code here
    s = s.strip()
    s = re.sub(' +', '_',s)
    return s

new_column_names = list(map(clean_column_name, list(df1.columns.values)))

# Here's our set of reformatted column names
new_column_names

['Per_capita_income',
 'Median_household_income',
 'Median_family_income',
 'Population',
 'Number_of_households',
 'Number_of_families']

Now we can reset the column names.

In [35]:
df1.columns = new_column_names
df1.head()

                     Per_capita_income Median_household_income Median_family_income  Population  Number_of_households  Number_of_families
State
District of Columbia           $45,877                 $71,648              $84,094      658893                277378              117864
Connecticut                    $39,373                 $70,048              $88,819     3596677               1355817              887263
New Jersey                     $37,288                 $69,160              $87,951     8938175               2549336             1610581
Massachusetts                  $36,593                 $71,919              $88,419     6938608               3194844             2203675
Maryland                       $36,338                 $73,971              $89,678     5976407               2165438             1445972

That's better!

Let’s say we were interested in identifying states that had a large divergence between Median household income and Median family income. 

Per the Census Bureau’s [definitions](https://www.census.gov/programs-surveys/cps/technical-documentation/subject-definitions.html#familyhousehold), a family is “a group of two people or more (one of whom is the householder) related by birth, marriage, or adoption and residing together; all such people (including related subfamily members) are considered as members of one family.” Conversely, a household “consists of all the people who occupy a housing unit.”

In [ ]:
df1.Median_family_income - df1.Median_household_income

Uh oh --- that did not work – what’s wrong?

In [ ]:
df1.info()

This does not work becuase these two columens are represented by strings rather than ints or float objects. On import, pandas interpreted them as strings rather than floats or ints because of the '\$' symbols in them. Let's use our clean_int function from last time to solve this issue.  (Notice, that clean_int now replaces '\$' symbols too.)  If we 'apply' clean_int to the Per_capita_income column, we get the following:

In [ ]:
df1['Per_capita_income'].apply(clean_int)

Since we have three such columns to deal with, let's clean them in bulk.

In [ ]:
for colname in ['Per_capita_income', 'Median_household_income', 'Median_family_income']:
    df1[colname] = df1[colname].apply(clean_int)

In [ ]:
df1.head()

Why does this work?  Aren't we changing the columns as we go?

Now let’s get back to looking at the difference between median household and family by state.

In [ ]:
df1['Household_family_diff'] = df1.Median_family_income - df1.Median_household_income
df1.head()

Let’s identify the states with the largest differential...

In [ ]:
key_cols = ['Median_family_income','Median_household_income','Household_family_diff']
df1.sort_values(['Household_family_diff'],ascending=False)[key_cols].head(5)

And the smallest...

In [ ]:
df1.sort_values(['Household_family_diff'])[key_cols].head(5)

## Plot our data!

In [ ]:
y_values = (df1['Household_family_diff']).sort_values(ascending=False)
x_values = list(y_values.index)
x_pos = np.arange(len(y_values))

plt.bar(x_pos,y_values, align='center', alpha=0.5)
plt.xticks(x_pos, x_values, rotation=90, fontsize=12)
plt.ylabel('Difference between family income and household income (USD)')
plt.title('Difference between Median family income and median household income by state')

new_style = {'grid': False}
plt.rc('axes', **new_style)
plt.rc

We can make almost the exact same chart using Panda’s  built in “plot” command with much less code.

In [ ]:
df1['Household_family_diff'].sort_values(ascending=False).plot(kind="bar", alpha=.5, fontsize=12)
plt.ylabel('Difference between family income and household income (USD)')
plt.title('Difference between Median family income and median household income by state')

## Combine dataframes

What if we want to combine out two dataframes?   There are a number of ways to do this.  

One way is to use the Pandas concat function.  It stitches the two data frames together based on their **index values**.

In [ ]:
result = pd.concat([df, df1], axis=1, join='inner')
print(len(result))
result.head()

Let's check the results by comparing the 'Connecticut' from each of the constituent dataframes.

In [ ]:
df.loc['Connecticut']

In [ ]:
df1.loc['Connecticut']

Notice that we can also do an 'outer' join.  What's the difference?

In [ ]:
result = pd.concat([df, df1], axis=1, join='outer')
print(len(result))
result

Notice that “District of Columbia” is listed twice above. What’s going on? Why didn’t it match?

In [ ]:
df.index[8]

In [ ]:
df1.index[0]

In [ ]:
df.index[8] == df1.index[0]

Note even though the strings *look* the same, slight differences in the way the strings are encoded keep pandas from matching them up. If we wanted to fix this, we’d probably want to go back to the import stage and do it there. Adjusting indexes once they’ve been assigned is messy in pandas.

In [ ]:
result = pd.concat([df, df1], axis=1, join='inner')

Another approach is to use the merge method on the shared values in two specified columns.  Let's explore this by copying the index column to a column of a slightly different name.  (If we had available some other shared key, we could use that.)

In [ ]:
df['state'] = df.index
df1['state'] = df1.index

In [ ]:
combined_df= df1.merge(df, on='state', how='inner')
len(combined_df)

In [ ]:
combined_df.head()

Note here that the while the resulting table is correct, we’ve abounded our index which makes the table harder to work with.

## Analysis on joined frame – what drives household income?

Finally, let’s explore a couple of possible drivers of median household income.

In [ ]:
plt.scatter(combined_df['2010']/1e6, combined_df['Median_household_income']/1e3)

plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.title("Median income vs population by State")
plt.xlabel("Population (Millions)")
plt.ylabel("Median household income (Thousands)")

Perhaps we think population *growth*, rather than raw size is what matters…

In [ ]:
population_growth = result['2010']/result['1980']
population_growth

In [ ]:
plt.title("Population growth by state, 1980-2010")
population_growth.sort_values(ascending=False).plot(kind='bar')
plt.axhline(y=1, color='r', linestyle='-')
# Draw a dotted line at y=1
plt.ylabel("30 year population growth multiplier")

In [ ]:
plt.scatter(population_growth, combined_df.Median_household_income/1e3)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.title("Median income vs population growth by State")
plt.xlabel("30 year population growth multiplier")
plt.ylabel("Median household income (Thousands)")